spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /admin/health
        healthCheckInterval: 15s
        instance-id: consul-server
  application:
    name: consul-server
server:
  port: 8502
